### ISSUE TITLE
Documentation site is down

### ISSUE THREAD

**Issue by farmdawgnation** [traefik/mesh#731]
## Bug Report

The documentation site is down

### What did you do?

Attempted to visit the documentation site.

### What did you expect to see?

The documentation site.

### What did you see instead?

![Screen Shot 2020-09-16 at 1 32 01 PM](https://user-images.githubusercontent.com/620189/93371851-02096200-f821-11ea-8b48-7c3ed8e98fc7.png)

### Output of controller log: (_What version of Traefik Mesh are you using?_)

N/A

### What is your environment & configuration (arguments, provider, platform, ...)?

N/A

### If applicable, please paste the yaml objects required to reproduce your issue

N/A

**Comment by ldez** [comment]
Hello, thank you for reporting this issue.

As a workaround, you can use https://traefik.github.io/mesh/

**Comment by mmatur** [comment]
Hello @farmdawgnation, 

Thanks for the report.

 The site is back in the game. It was a DNS issue.
