### ISSUE TITLE
Rework the API endpoints to be more restful

### ISSUE THREAD

**Issue by kevinpollet** [traefik/mesh#749]
### Proposal

The API is currently debug oriented and some endpoints path are not Restful:
- /api/configuration/current ⇒ /api/configuration
- /api/topology/current ⇒ /api/topology 
- /api/status/nodes ⇒ /api/nodes

Some REST endpoints should be removed or intentionally not documented.

**Comment by jspdown** [comment]
@kevinpollet I'm not sure we want to document `/api/nodes`. This really debug oriented.

**Comment by kevinpollet** [comment]
@jspdown I agree and I’m not sure that it makes sense to keep it.

**Comment by SantoDE** [comment]
did we ever need it really? :P

**Comment by jspdown** [comment]
@SantoDE The API was used mostly for a debugging purpose. The only 2 endpoints that are really useful are the one for getting the dynamic configuration and the one for the topology.
