### ISSUE TITLE
Add the supported SMI spec versions in the compatibility section

### ISSUE THREAD

**Issue by kevinpollet** [traefik/mesh#768]
### Proposal

Currently, the [compatibility](https://doc.traefik.io/traefik-mesh/compatibility/) section of the documentation lists only the supported versions of Kubernetes. To be more precise on the SMI spec versions supported by Traefik Mesh we should add a sub-section to list the supported versions of the SMI specs.

**Comment by traefiker** [comment]
Closed by #770.
