### ISSUE TITLE
Onboarding network debugging instructions

### ISSUE THREAD

**Issue by pcj** [traefik/mesh#804]
After doing a standard helm install and following the client.yaml/server.yaml test instructions, I am observing:

```
/ # curl server.test.traefik.mesh
curl: (6) Could not resolve host: server.test.traefik.mesh
```

Help on debugging this appreciated

I'd be happy to add this to the current onboarding tutorial if resolved.

**Comment by kevinpollet** [comment]
Hello @pcj,

We dedicate the issue tracker to bug reports and feature requests only.

For questions related to Traefik Mesh, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik Mesh section](https://community.traefik.io/c/traefik-mesh).

Don't hesitate to give more information (version used, logs, ...) and more explanations about what you are trying to achieve.

**Comment by gibbonsryan** [comment]
@pcj did you ever find an answer for this? I am having the same exact issue.

**Comment by pcj** [comment]
@gibbonsryan I can't recall the details, but I moved on from trying to use traefik/mesh as it did not seem to be very actively developed.  Maybe things have picked up since my initial attempt.

**Comment by gibbonsryan** [comment]
@pcj just a heads up, my issue may have been different but I was using AWS EKS and the coredns addon was self-reconciling through "managedfields" so the mesh patch was immediately being overwritten.
