### ISSUE TITLE
Please Support CoreDNS version 1.9.0

### ISSUE THREAD

**Issue by supanadit** [traefik/mesh#821]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/mesh/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik Mesh community forum](https://community.traefik.io/c/traefik-mesh) and didn't find any.

### Proposal

![image](https://user-images.githubusercontent.com/33617149/170828640-dd4d421c-6e72-4382-b86c-9c8bea8860eb.png)

Please support CoreDNS version 1.9.0

### Background

I am using MicroK8s, and latest version of MicroK8s using CoreDNS 1.9.0 then i install traefik-mesh using helm chart and error message showing that "Unsuported CoreDNS version 1.9.0"

### Workarounds

I don't think there's any solution for MicroK8S, or installing different CoreDNS like downgrade the version, because CoreDNS in Microk8S has special configuration and it's included as Core Addons.

**Comment by adyanth** [comment]
K3s with CoreDNS 1.9.1 here, same issue, cannot install/clean uninstall the helm chart due to the same issue.

**Comment by traefiker** [comment]
Closed by #824.
