### ISSUE TITLE
Make DNS configuration (opt-in) configurable

### ISSUE THREAD

**Issue by dtomcej** [traefik/mesh#89]
We may not want users to opt-out of the mesh. This could be configured during helm install, and we could patch a coreconfig that replaces the default.

**Comment by dtomcej** [comment]
I think that #250 is a better implementation idea for this.

Don't allow non-mesh traffic via k8s object, rather than hijacking all DNS requests.

**Comment by jspdown** [comment]
Closing this in favor or #250
